/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_NativeUtil */

#ifndef _Included_util_NativeUtil
#define _Included_util_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_NativeUtil
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_NativeUtil_hello
  (JNIEnv *, jclass);

/*
 * Class:     util_NativeUtil
 * Method:    buildPaginationHtml
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_util_NativeUtil_buildPaginationHtml__
  (JNIEnv *, jclass);

/*
 * Class:     util_NativeUtil
 * Method:    buildPaginationHtml
 * Signature: (IIIIIIIILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_util_NativeUtil_buildPaginationHtml__IIIIIIIILjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
